platform :ios, "10.0"
project "NormalSpec.xcodeproj"

target :NormalSpec do
  pod "ModelMapper", path: "../../.."
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["SWIFT_TREAT_WARNINGS_AS_ERRORS"] = "YES"
  end
end
