platform :ios, "10.0"
project "NoConvertibles.xcodeproj"

target :NoConvertibles do
  pod "ModelMapper/NoConvertibles", path: "../../.."
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["SWIFT_TREAT_WARNINGS_AS_ERRORS"] = "YES"
  end
end
